### ISSUE TITLE
Compatibility with JitPack (or a Maven Repo)

### ISSUE THREAD

**Issue by HeroCC** [JacisNonsense/Pathfinder#17]
When trying to use [JitPack](https://jitpack.io/#JacisNonsense/Pathfinder) (a free maven repository for any public github repo) to download Pathfinder, the build fails with [this](https://jitpack.io/com/github/JacisNonsense/Pathfinder/1.5/build.log) error log. It looks like it is trying to install the libraries to a prefix only accessible by root. Is there a way to have it build correctly when it can't access that location? (Dumping the built objects into a local directory instead of the default global?)
I made a similar ticket on JitPack [here](https://github.com/jitpack/jitpack.io/issues/1889)

Alternatively, is there a maven repo setup to host Pathfinder artifacts?

Thanks!

**Comment by JacisNonsense** [comment]
This issue seems a bit half-and-half in terms of what's causing the problem. On one hand, we state in the README that `./gradlew install` will install native binaries to /usr/local by default unless overridden, with is a root-required directory.

On the other hand, why does Jitpack run `./gradlew install` instead of `./gradlew uploadArtifacts`, which doesn't conflict with the native platform?

I'm not certain it's a good idea to host a complex multi-project repo like Pathfinder on jitpack, since the nativeplatform backs the entire project. Maven may be supported at some point, Pathfinder isn't very high on my projects list at this time.

**Comment by edelmanjm** [comment]
With the new ~~year~~ build season upon us, I'm curious if this if the anything's changed regarding this issue.

**Comment by JacisNonsense** [comment]
Pathfinder has some releases on http://dev.imjac.in/maven
They are currently unstable, I'm working on getting them stable today

**Comment by JacisNonsense** [comment]
With GradleRIO 2018.01.11 you can use the following:
###Java:
```gradle
compile pathfinder()
```
###C++
```gradle
lib library: "pathfinder"
```

**Comment by edelmanjm** [comment]
Should this info be added to the README?

**Comment by JacisNonsense** [comment]
I will after work
